version: '3'

services:
  tracking-solution:
    build: .
    image: tracking-solution:latest
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig
      - .:/workspace
    working_dir: /workspace
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY

