cmake_minimum_required (VERSION 3.20)
project(tracker-rbr)
add_executable(tracker_rbr main.cpp)
add_library(tracker tracker.cpp)
set_target_properties(tracker PROPERTIES PUBLIC_HEADER tracker.h types.h serialization.h)
include_directories(BEFORE ${CMAKE_PREFIX_PATH}/include ${CMAKE_CURRENT_SOURCE_DIR})
target_link_directories(tracker BEFORE PUBLIC ${CMAKE_PREFIX_PATH}/lib)
target_link_libraries(tracker_rbr docopt pthread rt)
set_property(TARGET tracker PROPERTY CXX_STANDARD 17)
install(TARGETS tracker PUBLIC_HEADER DESTINATION include)
install(TARGETS tracker DESTINATION lib)
install(TARGETS tracker_rbr DESTINATION bin)

